<a href="https://colab.research.google.com/github/Ikhadija-5/AMMI-BootCamp-Project/blob/main/Generating_Processed_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/IMDB Dataset.csv')
df.head(5)

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
import preprocessing

In [ ]:
df['review'] = df['review'].apply(preprocessing.remove_punc)
df.head(5)

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production br br The filmin...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically theres a family where a little boy J...  negative
4  Petter Matteis Love in the Time of Money is a ...  positive

In [ ]:
df['review'] = df['review'].apply(preprocessing.lowercase)
df.head(5)

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production br br the filmin...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

In [ ]:
df['review'] = df['review'].apply(preprocessing.remove_whitespace)
df.head(5)

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production br br the filmin...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

In [ ]:
df['review'] = df['review'].apply(preprocessing.remove_special_characters)
df.head(5)

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production br br the filmin...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

In [ ]:
df['review'] = df['review'].apply(preprocessing.remove_stopwords)
df.head(5)

                                              review sentiment
0  one reviewers mentioned watching 1 oz episode ...  positive
1  wonderful little production br br filming tech...  positive
2  thought wonderful way spend time hot summer we...  positive
3  basically theres family little boy jake thinks...  negative
4  petter matteis love time money visually stunni...  positive

In [ ]:
df['review'] = df['review'].apply(preprocessing.stemmer)
df.head(5)

                                              review sentiment
0  one review mention watch 1 oz episod youll hoo...  positive
1  wonder littl product br br film techniqu unass...  positive
2  thought wonder way spend time hot summer weeke...  positive
3  basic there famili littl boy jake think there ...  negative
4  petter mattei love time money visual stun film...  positive

In [ ]:
#Saving to a csv file
df.to_csv('/content/Clean_data.csv',index = False)

In [ ]:
df_clean = pd.read_csv('/content/Clean_data.csv')

In [ ]:
df_clean

                                                  review sentiment
0      one review mention watch 1 oz episod youll hoo...  positive
1      wonder littl product br br film techniqu unass...  positive
2      thought wonder way spend time hot summer weeke...  positive
3      basic there famili littl boy jake think there ...  negative
4      petter mattei love time money visual stun film...  positive
...                                                  ...       ...
49995  thought movi right good job wasnt creativ orig...  positive
49996  bad plot bad dialogu bad act idiot direct anno...  negative
49997  cathol taught parochi elementari school nun ta...  negative
49998  im go disagre previou comment side maltin one ...  negative
49999  one expect star trek movi high art fan expect ...  negative

[50000 rows x 2 columns]